### ISSUE TITLE
A typo in error message

### ISSUE THREAD

**Issue by yokochi47** [uwbmrb/PyNMRSTAR#104]
Hi Jon,

I noticed a typo in error message, saveframe.py, line 579:
                raise ValueError('The Sf_framecode tag cannot be different from the saveframe name. Error '
                                 f'occurred in tag {self.tag_prefix}.Sf_framecode with value {value} which '
                                 f'conflicts with **with** the saveframe name {self._name}.')

Could you please fix this?

**Comment by jonwedell** [comment]
Hey Masashi,

My apologies I didn't get to this sooner, but 3.3 is released with this fix. I also made some major improvements in the Loop.add_data() method that are probably worth reading about for future use: https://pynmrstar.readthedocs.io/en/latest/usage/full.html#pynmrstar.Loop.add_data

Have a good weekend!

**Comment by yokochi47** [comment]
Hi Jon,

I'm happy to hear that the enhancements to Loop.add_data () can be very helpful in improving the readability of own application.

Thank you for the fix and information.
