### ISSUE TITLE
pynmrstar library should not use logging.basicConfig

### ISSUE THREAD

**Issue by epeisach** [uwbmrb/PyNMRSTAR#106]
It is considered bad form for a library to use logging.basicConfig.   It establishes the logging format for the application if the import happens before logging is defined in the code with the main function.

Consider the following in the main application - with a typical code style - imports before functional code.

import logging
import pynmrstar

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s]-%(module)s.%(funcName)s: %(message)s")

As pynmrstar has done this already in the import - it overrides what is being specified. 

In addition, a library should not set the root logging level.  This should again be determined by the application.

**Comment by jonwedell** [comment]
Hey @epeisach - apologies on the delay on this one. I was on vacation the week this was files and it got lost when I returned.

Thanks for bringing this to my attention - I've updated the logging code to reflect your suggestions and best practices. If you have a few minutes, I'd appreciate it if you could review the changes to ensure they are satisfactory before I put out a new release. The relevant commit is visible [here](https://github.com/bmrb-io/PyNMRSTAR/commit/0cf013011aebdea015d9abc3014dabbd16af0190).

Cheers,
Jon

**Comment by epeisach** [comment]
Wouldn't you change have the same affect?  You are deciding the log level and formatting for a library?
Shouldn't I as the consumer be able to specify this?

I am not sure - but if I already have a stream handler defined for the root logging - will I then get double messages from pynmrstar?

**Comment by jonwedell** [comment]
Resolved in newly released version 3.3.1.

Release notes: https://pynmrstar.readthedocs.io/en/latest/release-notes.html#id1
