### ISSUE TITLE
odd behaviour of frame_codes

### ISSUE THREAD

**Issue by varioustoxins** [uwbmrb/PyNMRSTAR#107]
when I create a frame with 

```python
frame = Saveframe.from_scratch(frame_code, category)
```

and use something like `frame_code = nef_chemical_shift_list_nmrpipe` when I do

```python
     frame.add_tag("sf_category", category)
```

I get 

```
save_nef_chemical_shift_list_nmrpipe
   _nef_chemical_shift_list.sf_category   nef_chemical_shift_list
   _nef_chemical_shift_list.sf_framecode  nef_chemical_shift_list_nmrpipe

   loop_
      _nef_chemical_shift_list.chain_code
    ...
```

whereas I expected 

```
save_nef_chemical_shift_list_nmrpipe
   _nef_chemical_shift_list_nmrpipe.sf_category   nef_chemical_shift_list
   _nef_chemical_shift_list_nmrpipe.sf_framecode  nef_chemical_shift_list_nmrpipe

   loop_
      _nef_chemical_shift_list.chain_code
    ...
```

is this correct, is nef treating star file frames in an odd way

**Comment by dmaziuk** [comment]
Terms are a bit confusing: "category" is saveframe type, "framecode" is saveframe name. They don't have to be the same (and arguably shouldn't be). You'd normally have categories defined in your data model; names are arbitrary.

The `sf_framecode` tag must contain the exact name as in `save_nef_chemical_shift_list_nmrpipe` -- it exists for simple relational mapping: the place to store saveframe name in a database table.

**Comment by varioustoxins** [comment]
Hi

I think I follow what I need to do now, your comments sent me back to read the api and I understand more now, I wasn't aware the tag prefix and sf_name could be unrelated.

so now I have 

```python
frame = Saveframe.from_scratch(frame_code, frame_code)

frame.add_tag("sf_category", category)
```

this gives me 

```
save_nef_chemical_shift_list_nmrpipe
   _nef_chemical_shift_list_nmrpipe.sf_category   nef_chemical_shift_list
   _nef_chemical_shift_list_nmrpipe.sf_framecode  nef_chemical_shift_list_nmrpipe

save_
```

so in nef the sf_name and tag_prefix will always be the same.... its just the way they have written there standard... I guess
