### ISSUE TITLE
warnings give no information about location of deprecations in user code

### ISSUE THREAD

**Issue by varioustoxins** [uwbmrb/PyNMRSTAR#119]
warnings such as the one at 556 in loop.py provide no information as to where  the user function that called the deprecated function is located

**Comment by jonwedell** [comment]
You can cause warnings to be treated like exceptions (with a full stack trace) by running

```
import warnings
warnings.filterwarnings('error')
```

before using PyNMR-STAR, or if you only want to have that behavior for this specific warning:

```
import warnings
warnings.filterwarnings('error', 'Deprecated: It is recommended')
```

Alternatively, you can keep them as warnings but with a full stack trace by following the instructions here: https://stackoverflow.com/questions/22373927/get-traceback-of-warnings

My understanding is that it is up to calling code to decide what (if anything) to do with warnings. One of the benefits of adding the warning is also having the function show as deprecated in many IDEs. Here is an example of what I see if I try to use the function in PyCharm:

![image](https://github.com/bmrb-io/PyNMRSTAR/assets/5184895/ba0ffc5d-3d8d-4893-b660-39666d066ae8)

**Comment by varioustoxins** [comment]
Hi John Thanks for the info, I saw the same and tracked it down but wonder if more nieve users would wonder what file was causing it that's all
