### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by ktamiola** [uwbmrb/PyNMRSTAR#70]
It would be great to have some simple examples, e.g. reading in the data, looping over conditions etc.

**Comment by jonwedell** [comment]
Hello Kamil,

Thanks for the feedback. I'm working on a both a quick-start document and examples document today; I'll let you know when they are posted.

Regards,
Jon

**Comment by ktamiola** [comment]
Thank you so much for a swift response Jon. I am pretty sure it is a lot of work to manage the repository alone. I do believe, however, a few short examples will vastly improve "the value proposition" of the library.

**Comment by jonwedell** [comment]
@ktamiola - I have updated the main readme to serve as an introduction to the library, moved the full documentation to a separate file, and created an additional examples file.

New overview: https://github.com/uwbmrb/PyNMRSTAR/tree/v2-dev
Examples: https://github.com/uwbmrb/PyNMRSTAR/blob/v2-dev/documentation/examples.md
Full documentation: https://github.com/uwbmrb/PyNMRSTAR/blob/v2-dev/documentation/full.md

If you have any specific use cases or things you are attempting to do with the library that you didn't find clear documentation for it would be great for me to use them as a basis to create more documentation.

@dmaziuk  @elulrich @kumar-physics @perzeus - Any feedback on the new main documentation page? It has a brief overview of the NMR-STAR format now as well.

**Comment by kumar-physics** [comment]
Examples are good and very useful, but covers only parsing. It would be good to have some exampled to write the data, because software developers may want to output their data  in NMR-STAR.  Example of creating saveframes and loops may be useful for the software community. 
Kumaran

**Comment by jonwedell** [comment]
@kumar-physics Added creation/writing examples.

Closed by #71.
