### ISSUE TITLE
ValueError: You cannot have two loops with the same category in one saveframe

### ISSUE THREAD

**Issue by dspoel** [uwbmrb/PyNMRSTAR#77]
I made a very simple script based on the README file:

#!/usr/bin/env python3

import pynmrstar

entry = pynmrstar.Entry.from_file("1l2y_mr.str")
entry.print_tree()

where 1l2y_mr.str was freshly downloaded from https://www.rcsb.org/structure/1l2y
This gives me the following output:

% ./nmrstar_test.py
Traceback (most recent call last):
  File "./nmrstar_test.py", line 5, in <module>
    entry = pynmrstar.Entry.from_file("1l2y_mr.str")
  File "/home/spoel/wd/PyNMRSTAR/pynmrstar.py", line 1755, in from_file
    return cls(file_name=the_file)
  File "/home/spoel/wd/PyNMRSTAR/pynmrstar.py", line 1558, in __init__
    parser.parse(star_buffer.read(), source=self.source)
  File "/home/spoel/wd/PyNMRSTAR/pynmrstar.py", line 743, in parse
    curframe.add_loop(curloop)
  File "/home/spoel/wd/PyNMRSTAR/pynmrstar.py", line 2554, in add_loop
    loop_to_add.category)
ValueError: You cannot have two loops with the same category in one saveframe. Category: '_Constraint_file'.

Is the input file broken or the script? The file 2lot_mr.str gives the same problem.

**Comment by jonwedell** [comment]
I took a look and the input file is invalid NMR-STAR. I will contact the RCSB to resolve it and see if it is a more systematic issue.

In the meantime, the invalid part of the file is

```
   loop_
      _Constraint_file.ID
      _Constraint_file.Constraint_filename
      _Constraint_file.Software_ID
      _Constraint_file.Software_label
      _Constraint_file.Software_name
      _Constraint_file.Block_ID
      _Constraint_file.Constraint_type
      _Constraint_file.Constraint_subtype
      _Constraint_file.Constraint_subsubtype
      _Constraint_file.Constraint_number
      _Constraint_file.Entry_ID
      _Constraint_file.Constraint_stat_list_ID

      1 "From CCPN project: '1l2y'" . . . . distance "general distance" . 169 rr_1l2y 1 

   stop_

   loop_
      _Constraint_file.ID
      _Constraint_file.Constraint_filename
      _Constraint_file.Software_ID
      _Constraint_file.Software_label
      _Constraint_file.Software_name
      _Constraint_file.Block_ID
      _Constraint_file.Constraint_type
      _Constraint_file.Constraint_subtype
      _Constraint_file.Constraint_subsubtype
      _Constraint_file.Constraint_number
      _Constraint_file.Entry_ID
      _Constraint_file.Constraint_stat_list_ID

      1 1l2y.mr . . "MR format" 1  comment               "Not applicable" "Not applicable"   0 rr_1l2y 1 
      1 1l2y.mr . .  XPLOR/CNS  2  distance               NOE              simple          169 rr_1l2y 1 
      1 1l2y.mr . . "MR format" 3 "nomenclature mapping" "Not applicable" "Not applicable"   0 rr_1l2y 1 

   stop_
```

Either delete the first _constraint_file loop, or replace both with this one:

```
   loop_
      _Constraint_file.ID
      _Constraint_file.Constraint_filename
      _Constraint_file.Software_ID
      _Constraint_file.Software_label
      _Constraint_file.Software_name
      _Constraint_file.Block_ID
      _Constraint_file.Constraint_type
      _Constraint_file.Constraint_subtype
      _Constraint_file.Constraint_subsubtype
      _Constraint_file.Constraint_number
      _Constraint_file.Entry_ID
      _Constraint_file.Constraint_stat_list_ID

      1 1l2y.mr . . "MR format" 1  comment               "Not applicable" "Not applicable"   0 rr_1l2y 1 
      1 1l2y.mr . .  XPLOR/CNS  2  distance               NOE              simple          169 rr_1l2y 1 
      1 1l2y.mr . . "MR format" 3 "nomenclature mapping" "Not applicable" "Not applicable"   0 rr_1l2y 1 
     2 "From CCPN project: '1l2y'" . . . . distance "general distance" . 169 rr_1l2y 1 
   stop_
```

If multiple saveframes in the file have the same problem, you will need to make the fix for all of them.

**Comment by dspoel** [comment]
Thanks for the quick response. As the issue occurred in both files I tried we will wait for the rcsb response and try to familiarize with other aspects of the software :)

**Comment by jonwedell** [comment]
@epeisach - can you help with this, or point me to whom I should get in contact with?

**Comment by snehal77patel** [comment]
We are trying to extract NOE distance restraints from .str file. Is that suppose to work?

**Comment by jonwedell** [comment]
> We are trying to extract NOE distance restraints from .str file. Is that suppose to work?

Yes, that should work. The file dspoel referenced contains NOE distance restraints in the `save_CNS/XPLOR_distance_constraints_2` saveframe.

I've attached a fixed version of the file that you can read with the PyNMR-STAR library and a CSV version of the distance restraints(1) (saved as .txt files because GitHub wouldn't accept the upload of CSV or STR).

I have a meeting on Thursday where I'll be able to discuss this error with the RCSB team and see that it gets resolved.

1) Generated using:

```python
import pynmrstar
entry = pynmrstar.Entry.from_file("1l2y_mr.str")
# If there were multiple NOE constraint loops, you would need to iterate over the results
constraints = entry.get_loops_by_category('_Gen_dist_constraint')[0]
# print(constraints.data)
open('1l2y.csv', 'w').write(constraints.get_data_as_csv())
```


[1l2y.csv.txt](https://github.com/uwbmrb/PyNMRSTAR/files/2932788/1l2y.csv.txt)
[1l2y_mr.str.txt](https://github.com/uwbmrb/PyNMRSTAR/files/2932789/1l2y_mr.str.txt)

**Comment by dspoel** [comment]
Cool, thanks. Indeed we did as you suggested and edited an input file to make it work. The plan is to generate input for refinement and analysis of MD simulations in the gromacs software.

**Comment by kumar-physics** [comment]
If you could add support for NMR-STAR files in GROMACS, that would be great. In future BMRB will provide all restraint data in NMR-STAR format. If you provide native support in GROMACS, then people can directly input NMR-SRTAR files. Feel free to contact us if you need any help.

**Comment by snehal77patel** [comment]
> > We are trying to extract NOE distance restraints from .str file. Is that suppose to work?
> 
> Yes, that should work. The file dspoel referenced contains NOE distance restraints in the `save_CNS/XPLOR_distance_constraints_2` saveframe.
@jonwedell 
Thank you for your suggestions.

**Comment by dspoel** [comment]
@jonwedell did anything come out of your meeting with the RCSB team?

**Comment by jonwedell** [comment]
We created an issue to track the problem in their issue tracker, but I don't have an idea of the time frame for the remediation at this point. @berrisfordjohn - do you know what sort of priority this issue will have?

I was planning on creating instructions on how to modify the PyNMR-STAR library to read these files despite the syntax error (probably via monkey-patching the parser, as it currently isn't set up to allow you to continue parsing once a syntax error is encountered). I should be able to provide that to you within the next two days.

**Comment by dmaziuk** [comment]
This looks like our bug, actually: see e.g. http://www.bmrb.wisc.edu/ftp/pub/bmrb/nmr_pdb_integrated_data/coordinates_restraints_chemshifts/divided/l2/1l2y/nmr-star/1l2y_linked.str

AFAICT this comes from merging coordinates and restraints: pre-merge the restraints file does not have the loop with "From CCPN project".

**Comment by dmaziuk** [comment]
PS at http://restraintsgrid.bmrb.wisc.edu/NRG/MRGridServlet you can get the not-yet-messed-up version of the file: type in PDB ID in the box up top and in the resulting table click on "2" in the  distance - NOE - simple row. You can then download the restraints in XPLOR or NMR-STAR.

**Comment by jonwedell** [comment]
@dmaziuk - Is this something you can fix for newly generated restraints? What steps will we need to take to remediate the old ones? I can provide code to merge the two loops.

**Comment by dmaziuk** [comment]
I have a feeling this has been set up by Wim Wranken, using his FormatConverter code, and bolted on to restraints processing pipeline somewhere. I would not know where. As of this moment the quickest is probably to re-process the files after they come out of the pipeline and before RCSB grabs them, but I have to try and step through that pipeline even to see where that point is.

**Comment by jonwedell** [comment]
@dspoel - We will work to see that these files are corrected on the source end, though that may take a while. I'll post here when it is complete.

In the meantime, I've written a tool you can use to read these files. Download [this file](https://raw.githubusercontent.com/uwbmrb/PyNMRSTAR/monkeypatch/monkeypatch.py) and then in python, before you try to read these files, run the following:

```python
import pynmrstar

# Patch the parser
from monkeypatch import patch_parser
patch_parser(pynmrstar)
```

After that, you should be able to read the files. The data from two loops are combined into one. I would try to avoid using this custom parser except for reading these specific invalid files. To restore the original parser after reading them, you could do something like

```python
import pynmrstar

# Patch the parser
from monkeypatch import patch_parser, unpatch_parser
patch_parser(pynmrstar)

# Read whatever files you need to
entry = pynmrstar.Entry.from_file(filename)

# Restore the original parser
unpatch_parser(pynmrstar)
```

**Comment by snehal77patel** [comment]
@jonwedell  Thank you for the script. It works perfectly.

**Comment by jonwedell** [comment]
I'm happy to hear that. I meant to mention in my previous comment, but please make sure you update pynmrstar to 2.6.4 (from here) or 2.6.4.1 (from PyPi) as I found a bug in the pynmrstar library that the monkeypatching code would trigger should you not update.

**Comment by snehal77patel** [comment]
Thanks again for the info.

**Comment by dmaziuk** [comment]
@jonwedell OK, the code that messes up the files is buried in a twisted maze of C-shell and python scripts, all alike. However, the resulting files are pushed out in a separate step. We can re-process the files at that point. If you have code to do that, we can add it to the mix.

This runs on an old host with python 2.5 though, if your code needs newer python we'll need to run it on the other side of the push. Let me know where it is/what it needs - if you have it, that is.

**Comment by jonwedell** [comment]
Hey Dimitri,

The code exists already, it is described above. PyNMR-STAR requires at least 2.6, so we will have to run it on the other side.

Set up the environment for doing the remediation (in whatever directory you want my code to live):

```bash
wget 'https://raw.githubusercontent.com/uwbmrb/PyNMRSTAR/monkeypatch/monkeypatch.py'
python -m virtualenv remediate
source remediate/bin/activate
pip install pynmrstar==2.6.4.1
deactivate
```

Do the remediation of one file:
```bash
source remediate/bin/activate
python2
```

then

```python
import pynmrstar
# Patch the parser
from monkeypatch import patch_parser
patch_parser(pynmrstar)

# Write to a different file name if you want to preserve the original
entry = pynmrstar.Entry.from_file(filename)
entry.write_to_file(filename)
```

This will all work in python3 as well, (except substituting the commands with their python3 equivalents) if the machine has it available.

**Comment by dmaziuk** [comment]
Looks like I have to talk to RCSB anyway: the files we think we're sending there are the ones before the merge (and error), the files they're publishing are the broken ones.

**Comment by jonwedell** [comment]
All of the files we generate have been remediated, and furthermore, synced to RCSB and EBI. I can verify that the constraint file for the PDB ID originally linked by @dspoel is now correct.

@dspoel  @snehal77patel - You should no longer need to use the monkey patch code when downloading these files. Thanks again for the report.
