### ISSUE TITLE
Document that python 3 is required in metadata so pip for python 2 will not go after newer versions

### ISSUE THREAD

**Issue by epeisach** [uwbmrb/PyNMRSTAR#85]
Too late for 3.0.3 -- but subsequent releases

Adding something like 
python_requires='>=3'

and for classifiers, 
Programming Language :: Python :: 3 :: Only

**Comment by jonwedell** [comment]
Thanks for bringing this to my attention.

3.0.4 released, with the proper `python_requires` and <3.0.4 releases yanked to get pip to install as expected.
